#!/usr/bin/env python3
"""Erzeugt scripts/build_investor_deck_de.js aus dem EN-Generator per exakter
Übersetzungstabelle. Bricht ab, wenn ein Quellstring nicht (genau) gefunden wird.
Aufruf: python3 scripts/make_deck_de.py && node scripts/build_investor_deck_de.js
"""

SRC = 'scripts/build_investor_deck.js'
DST = 'scripts/build_investor_deck_de.js'

# (english, german, expected_count)
T = [
    ("presentation/kronos-investor-deck.pptx", "presentation/kronos-investor-deck-de.pptx", 1),
    ("kronos-investor-deck.pptx geschrieben (20 Slides).", "kronos-investor-deck-de.pptx geschrieben (20 Slides, DE).", 1),

    # ---- Slide 1
    ("The dawn of accessible 3D-printed electronics.", "Der Aufbruch zu zugänglicher 3D-gedruckter Elektronik.", 1),
    ("Investment case for a 25k–100k € five-axis AME platform\\nbuilt on the technology of the category's pioneer.",
     "Investment Case für eine 5-Achs-AME-Plattform im Band 25–100 k€ —\\ngebaut auf der Technologie des Kategorie-Pioniers.", 1),
    ("INVESTOR DUE DILIGENCE PACKAGE   ·   AUGUST 2026   ·   CONFIDENTIAL",
     "INVESTOR DUE-DILIGENCE-PAKET   ·   AUGUST 2026   ·   VERTRAULICH", 1),

    # ---- Slide 2
    ('header(s, "Investment Opportunity", "An option-structured bet on the vacant middle of 3D-printed electronics")',
     'header(s, "Die Investment-Chance", "Eine optionsstrukturierte Wette auf die leere Mitte der 3D-Elektronik")', 1),
    ('"The ask"', '"Das Angebot"', 1),
    ('"€2.5M Tranche 1 "', '"2,5 M€ Tranche 1 "', 1),
    ('"of a €13.2M staged plan — committed only gate by gate."', '"eines gestuften 13,2-M€-Plans — committet nur Gate für Gate."', 1),
    ('"Proven 5-axis core technology — acquired at distressed cost from the Neotech insolvency"',
     '"Bewiesene 5-Achs-Kerntechnologie — zu Distressed-Kosten aus der Neotech-Insolvenz erworben"', 1),
    ('"Only vendor able to put true 5-axis AME below every procurement threshold"',
     '"Einziger Anbieter, der echtes 5-Achs-AME unter alle Vergabeschwellen bringen kann"', 1),
    ('"Category leadership vacant: Nano Dimension exited AME in April 2026"',
     '"Kategorie-Führung vakant: Nano Dimension stieg im April 2026 aus AME aus"', 1),
    ('"Honest framing: today\'s machine market is small — this is a market-creation bet with capped downside"',
     '"Ehrliches Framing: Der heutige Maschinenmarkt ist klein — eine Marktschaffungs-Wette mit gekapptem Downside"', 1),
    ('"What the staged €13.2M can build (Base case)"', '"Was die gestuften 13,2 M€ aufbauen können (Base Case)"', 1),
    ('"revenue 2031\\n(Base case)"', '"Umsatz 2031\\n(Base Case)"', 1),
    ('"machines installed\\nby 2031"', '"installierte Maschinen\\nbis 2031"', 1),
    ('"gross margin 2031,\\n19% recurring revenue"', '"Bruttomarge 2031,\\n19 % wiederkehrend"', 1),
    ('"EBITDA break-even\\n(Upside: 2030)"', '"EBITDA-Break-even\\n(Upside: 2030)"', 1),
    ('"MOIC in the Upside path\\n(IRR ≈ 48%, exit yr 7)"', '"MOIC im Upside-Pfad\\n(IRR ≈ 48 %, Exit J7)"', 1),
    ('"maximum at risk before\\nseries-production gate"', '"maximal im Risiko vor dem\\nSerien-Gate"', 1),

    # ---- Slide 3
    ('header(s, "KRONOS Today", "The pioneer\'s technology, reborn as a startup")',
     'header(s, "KRONOS heute", "Die Technologie des Pioniers, wiedergeboren als Start-up")', 1),
    ('"Neotech AMT develops 3D-printed electronics; installs world\'s first 5-axis 3D-PE system"',
     '"Neotech AMT entwickelt 3D-gedruckte Elektronik; weltweit erstes 5-Achs-3D-PE-System installiert"', 1),
    ('"First mass-production install — printed 3D antennas, millions of parts per year"',
     '"Erste Serieninstallation — gedruckte 3D-Antennen, Millionen Teile pro Jahr"', 1),
    ('"Neotech insolvency (AG Nürnberg). KRONOS Mechatronics acquires the assets"',
     '"Neotech-Insolvenz (AG Nürnberg). KRONOS Mechatronics übernimmt die Assets"', 1),
    ('"Relaunch Helios & Hyperion · APES partnership (North America) · productronica"',
     '"Relaunch Helios & Hyperion · APES-Partnerschaft (Nordamerika) · productronica"', 1),
    ('"LOPEC Start-up Award “Best Business Potential” · Aion-5X SDK published"',
     '"LOPEC Start-up Award „Best Business Potential" · Aion-5X-SDK veröffentlicht"', 1),
    ('"Technology"', '"Technologie"', 1),
    ('"Modular 5-axis platforms, ±5 µm; piezo-jet, inkjet, dispensing, FFF; plasma, UV, milling, SMD placement"',
     '"Modulare 5-Achs-Plattformen, ±5 µm; Piezo-Jet, Inkjet, Dispensing, FFF; Plasma, UV, Fräsen, SMD-Bestückung"', 1),
    ('"Software moat"', '"Software-Burggraben"', 1),
    ('"Aion-5X CAD/CAM: 5-axis simultaneous toolpaths, collision simulation, AI vision QC — with public SDK"',
     '"Aion-5X CAD/CAM: 5-Achs-Simultanbahnen, Kollisionssimulation, KI-Vision-QC — mit öffentlichem SDK"', 1),
    ('"Channels & visibility"', '"Kanäle & Sichtbarkeit"', 1),
    ('"APES + NTV (USA), Nürnberg AME cluster (FAPS/FAU), OE-A / LOPEC community"',
     '"APES + NTV (USA), Nürnberger AME-Cluster (FAPS/FAU), OE-A-/LOPEC-Community"', 1),
    ('"The honest gap"', '"Die ehrliche Lücke"', 1),
    ('"~6-person team, no verified sale since relaunch, patent chain-of-title unverified → gates V1–V7"',
     '"~6-Personen-Team, kein verifizierter Verkauf seit Relaunch, Patent-Titel ungeprüft → Gates V1–V7"', 1),

    # ---- Slide 4
    ('header(s, "The Problem", "Brilliant technology, trapped in a €200k+ project business")',
     'header(s, "Das Problem", "Brillante Technologie, gefangen im 200-k€-Projektgeschäft")', 1),
    ('"AME machines sold per year, worldwide, across all vendors (bottom-up)"',
     '"verkaufte AME-Maschinen pro Jahr, weltweit, alle Anbieter (Bottom-up)"', 1),
    ('"total annual AME machine market today — smaller than one mid-size Mittelstand firm"',
     '"gesamter AME-Maschinenmarkt heute — kleiner als ein einzelner Mittelständler"', 1),
    ('"of placements are grant-funded research buys — one-off, non-repeating"',
     '"der Platzierungen sind förderfinanzierte Forschungskäufe — einmalig, ohne Wiederkauf"', 1),
    ('"2024–2026: the category cleared itself out"', '"2024–2026: Die Kategorie hat sich selbst bereinigt"', 1),
    ('"The 5-axis pioneer — insolvent July 2024 after ~20 years and ~50 systems. Its assets became KRONOS."',
     '"Der 5-Achs-Pionier — insolvent Juli 2024 nach ~20 Jahren und ~50 Systemen. Seine Assets wurden KRONOS."', 1),
    ('"Raised ~$1.5B. Sold ~51 DragonFly systems. Exited AME in April 2026 for $2M upfront — the leader left at scrap value."',
     '"~1,5 Mrd. $ eingesammelt. ~51 DragonFly-Systeme verkauft. AME-Exit April 2026 für 2 M$ upfront — der Marktführer ging zum Schrottwert."', 1),
    ('"The Hensoldt-backed AME community platform — liquidated August 2025. The ecosystem lost its anchor."',
     '"Die Hensoldt-getragene AME-Community-Plattform — liquidiert August 2025. Das Ökosystem verlor seinen Anker."', 1),
    ('"The diagnosis: "', '"Die Diagnose: "', 1),
    ('"every player sold €150–500k project machines into a research niche. Nobody productized the technology for the budgets that actually buy lab equipment."',
     '"Alle verkauften 150–500-k€-Projektmaschinen in eine Forschungsnische. Niemand hat die Technologie für die Budgets produktisiert, die tatsächlich Laborgeräte kaufen."', 1),

    # ---- Slide 5
    ('header(s, "Why current machines limit the market", "Procurement thresholds decide who can buy — today\'s prices sit above all of them")',
     'header(s, "Warum heutige Maschinen den Markt begrenzen", "Vergabeschwellen entscheiden, wer kaufen darf — heutige Preise liegen über allen")', 1),
    ('"Optomec production ≈ €333k"', '"Optomec Produktion ≈ 333 k€"', 1),
    ('"EU tender threshold — €221k"', '"EU-Tender-Schwelle — 221 k€"', 1),
    ('"DFG review (university) — €200k  ·  Neotech 15X ≈ €200k"',
     '"DFG-Großgeräte (Uni) — 200 k€  ·  Neotech 15X ≈ 200 k€"', 1),
    ('"DE direct award (2025) · DFG HAW · NSF MRI — all ≈ €/$100k"',
     '"DE-Direktauftrag (2025) · DFG HAW · NSF MRI — alle ≈ 100 k€/$"', 1),
    ('"Below €100k, a machine purchase changes species"', '"Unter 100 k€ wird ein Maschinenkauf zu etwas anderem"', 1),
    ('"No EU tender, no DFG review — a department-level decision"',
     '"Kein EU-Tender, keine DFG-Prüfung — eine Abteilungsentscheidung"', 1),
    ('"Fits a single US faculty startup package ($300–500k)"',
     '"Passt in ein einzelnes US-Faculty-Startpaket (300–500 k$)"', 1),
    ('"German direct-award limit raised to €100k in 2025 — the door just opened"',
     '"Deutsche Direktauftragsgrenze 2025 auf 100 k€ erhöht — die Tür ist gerade aufgegangen"', 1),
    ('"Buying window: weeks, not budget years"', '"Kauffenster: Wochen, keine Haushaltsjahre"', 1),

    # ---- Slide 6
    ('header(s, "The Low-Cost Opportunity", "The 25–100k € band is empty — for the machines that matter")',
     'header(s, "Die Low-Cost-Chance", "Das Band 25–100 k€ ist leer — für die Maschinen, auf die es ankommt")', 1),
    ('"DESKTOP · <€12k"', '"DESKTOP · <12 k€"', 1),
    ('"€25–100k · THE GAP"', '"25–100 k€ · DIE LÜCKE"', 1),
    ('"INDUSTRIAL · >€150k"', '"INDUSTRIE · >150 k€"', 1),
    ('"Planar, education-grade.\\n5,000+ Voltera units prove the buyer base exists."',
     '"Planar, Education-Klasse.\\n5.000+ Voltera-Einheiten beweisen die Käuferbasis."', 1),
    ('"Voltera NOVA  ·  $46k  —  planar only"', '"Voltera NOVA  ·  46 k$  —  nur planar"', 1),
    ('"Fujifilm Dimatix  ·  ~$55k  —  planar only"', '"Fujifilm Dimatix  ·  ~55 k$  —  nur planar"', 1),
    ('"LPKF ProtoMat  ·  subtractive milling"', '"LPKF ProtoMat  ·  subtraktives Fräsen"', 1),
    ('"NO five-axis / conformal AME system exists here.\\nThe defining capability of 3D electronics is absent\\nfrom the only band procurement loves."',
     '"KEIN 5-Achs-/Konform-AME-System existiert hier.\\nDie definierende Fähigkeit der 3D-Elektronik fehlt\\nim einzigen Band, das die Vergabe liebt."', 1),
    ('"Quote-only project machines.\\nThe tier that bankrupted its pioneer."',
     '"Quote-only-Projektmaschinen.\\nDie Klasse, die ihren Pionier in die Insolvenz führte."', 1),

    # ---- Slide 7
    ('header(s, "Proof the band buys", "Machines at this price point sell in the thousands — just not additive 3D ones yet")',
     'header(s, "Beweis: Das Band kauft", "Maschinen zu diesem Preis verkaufen sich tausendfach — nur additive 3D-Systeme noch nicht")', 1),
    ('"Voltera units shipped to 92 countries — NASA, MIT, Harvard, Stanford, Oxford among customers"',
     '"Voltera-Einheiten in 92 Länder geliefert — Kunden u. a. NASA, MIT, Harvard, Stanford, Oxford"', 1),
    ('"The buyer universe is real and global"', '"Das Käuferuniversum ist real und global"', 1),
    ('"LPKF Development segment revenue 2024 — “thousands” of ProtoMat benchtop PCB machines installed"',
     '"LPKF-Development-Segmentumsatz 2024 — „Tausende" installierte ProtoMat-Benchtop-Systeme"', 1),
    ('"EE labs pay 10–60k € for in-house prototyping, for decades"',
     '"EE-Labore zahlen seit Jahrzehnten 10–60 k€ für Inhouse-Prototyping"', 1),
    ('"Formlabs printers sold after cutting professional SLA prices ~10x — a $2B company"',
     '"verkaufte Formlabs-Drucker nach ~10x-Preissenkung im Profi-SLA — ein 2-Mrd.-$-Unternehmen"', 1),
    ('"The 10x price-cut playbook works for professional machines"',
     '"Das 10x-Preissenkungs-Playbook funktioniert bei Profi-Maschinen"', 1),
    ('"XTPL Delta systems cumulative / delivered in 2025 alone at €170–220k — 71% research customers"',
     '"XTPL-Delta-Systeme kumuliert / allein 2025 geliefert, bei 170–220 k€ — 71 % Forschungskunden"', 1),
    ('"Even at 3x our price, research demand is accelerating"',
     '"Selbst beim 3-fachen unseres Preises beschleunigt die Forschungsnachfrage"', 1),

    # ---- Slide 8
    ('header(s, "New Customer Universe", "~10,000 organizations that could never buy a €250k machine")',
     'header(s, "Das neue Kundenuniversum", "~10.000 Organisationen, die nie eine 250-k€-Maschine kaufen konnten")', 1),
    ('["University research labs (EE/materials)", 1450]', '["Universitäre Forschungslabore (EE/Material)", 1450]', 1),
    ('["Corporate R&D — medtech SMEs", 1900]', '["Corporate R&D — Medtech-KMU", 1900]', 1),
    ('["Corporate R&D — electronics OEMs", 1800]', '["Corporate R&D — Elektronik-OEMs", 1800]', 1),
    ('["Education — HAW / eng. colleges", 1350]', '["Ausbildung — HAW / Colleges", 1350]', 1),
    ('["Automotive suppliers (IME, sensors)", 1100]', '["Automobilzulieferer (IME, Sensorik)", 1100]', 1),
    ('["Aerospace & defense R&D sites", 900]', '["Aerospace- & Defense-R&D", 900]', 1),
    ('["Research institutes / RTOs", 700]', '["Forschungsinstitute / RTOs", 700]', 1),
    ('["EMS & PCB prototyping services", 700]', '["EMS- & PCB-Dienstleister", 700]', 1),
    ('["FabLabs (institutional) + startups", 450]', '["FabLabs (institutionell) + Start-ups", 450]', 1),
    ('name: "Organizations"', 'name: "Organisationen"', 1),
    ('"Counted bottom-up, not asserted"', '"Bottom-up gezählt, nicht behauptet"', 1),
    ('"963 research-active EE universities (Research.com) · 76 Fraunhofer institutes · ZVEI 1,100+ · CLEPA 3,000+ · MedTech Europe 38,000 (90% SME) · in4ma 2,160 EMS · relevance-filtered per segment."',
     '"963 forschungsaktive EE-Unis (Research.com) · 76 Fraunhofer-Institute · ZVEI 1.100+ · CLEPA 3.000+ · MedTech Europe 38.000 (90 % KMU) · in4ma 2.160 EMS · je Segment relevanzgefiltert."', 1),
    ('"candidate organizations — vs. ~150 machines the industry sells per year today"',
     '"Kandidaten-Organisationen — vs. ~150 Maschinen, die die Branche heute pro Jahr verkauft"', 1),

    # ---- Slide 9
    ('header(s, "Market Segmentation", "One beachhead, two expansions — sequenced by procurement friction")',
     'header(s, "Marktsegmentierung", "Ein Beachhead, zwei Expansionen — sequenziert nach Beschaffungsfriktion")', 1),
    ('"BEACHHEAD · YEAR 1–2"', '"BEACHHEAD · JAHR 1–2"', 1),
    ('"EXPANSION · YEAR 2–3"', '"EXPANSION · JAHR 2–3"', 1),
    ('"EXPANSION · YEAR 3–5"', '"EXPANSION · JAHR 3–5"', 1),
    ('"Research labs & institutes (EU/NA)"', '"Forschungslabore & Institute (EU/NA)"', 1),
    ('"~2,150 organizations, tender-free below €100k"', '"~2.150 Organisationen, tender-frei unter 100 k€"', 1),
    ('"Technically tolerant — research forgives v1.0"', '"Technisch tolerant — Forschung verzeiht v1.0"', 1),
    ('"Every paper is a free reference (Voltera playbook)"', '"Jedes Paper ist eine Gratis-Referenz (Voltera-Playbook)"', 1),
    ('"KRONOS home turf: FAPS cluster, LOPEC award"', '"KRONOS-Heimvorteil: FAPS-Cluster, LOPEC-Award"', 1),
    ('"Corporate R&D — electronics, automotive/IME, medtech"', '"Corporate R&D — Elektronik, Automotive/IME, Medtech"', 1),
    ('"Reference-driven entry from beachhead"', '"Referenzgetriebener Einstieg aus dem Beachhead"', 1),
    ('"IP-sensitive iteration stays in-house"', '"IP-sensible Iteration bleibt im Haus"', 1),
    ('"IME pre-development without tooling cost"', '"IME-Vorentwicklung ohne Werkzeugkosten"', 1),
    ('"~4,800 filtered organizations"', '"~4.800 gefilterte Organisationen"', 1),
    ('"Defense & space labs · education fleets · small series"', '"Defense- & Space-Labs · Ausbildungsflotten · Kleinserie"', 1),
    ('"DoD AM budget: $0.3B → $0.8B → ~$2.6B (2030e)"', '"DoD-AM-Budget: 0,3 → 0,8 → ~2,6 Mrd. $ (2030e)"', 1),
    ('"Eos Max + traceability via APES/NTV"', '"Eos Max + Traceability über APES/NTV"', 1),
    ('"Eos One curriculum bundles"', '"Eos-One-Curriculum-Bundles"', 1),
    ('"Production cells feed Hyperion upsell"', '"Produktionszellen speisen den Hyperion-Upsell"', 1),

    # ---- Slide 10
    ('header(s, "Use Cases", "Jobs to be done — what a €65k five-axis machine gets hired for")',
     'header(s, "Use Cases", "Jobs to be done — wofür eine 65-k€-5-Achs-Maschine engagiert wird")', 1),
    ('"Publish first"', '"Zuerst publizieren"', 1),
    ('"“Print the 3D antenna / conformal sensor the competing group can\'t.” Five-axis capability is publication-grade differentiation — the strongest academic buying motive."',
     '"„Drucke die 3D-Antenne / den konformen Sensor, den die Konkurrenzgruppe nicht kann." 5-Achs-Fähigkeit ist Publikations-Differenzierung — das stärkste akademische Kaufmotiv."', 1),
    ('"Iterate same-day"', '"Am selben Tag iterieren"', 1),
    ('"“From CAD to functional 3D circuit before the evening — not a 3-week offshore loop.” Substitutes cap value only for flat standard PCBs; 3D iteration has no substitute."',
     '"„Vom CAD zur funktionalen 3D-Schaltung vor dem Abend — statt 3-Wochen-Offshore-Schleife." Substitute deckeln nur flache Standard-PCBs; 3D-Iteration hat kein Substitut."', 1),
    ('"Keep IP in-house"', '"IP im Haus behalten"', 1),
    ('"“Defense, automotive pre-development and medical prototypes never leave the building.” ITAR/IP-sensitive work structurally cannot use board services."',
     '"„Defense, Automotive-Vorentwicklung und Medizin-Prototypen verlassen nie das Gebäude." ITAR-/IP-sensible Arbeit kann strukturell keine Board-Services nutzen."', 1),
    ('"Train the next cohort"', '"Die nächste Kohorte ausbilden"', 1),
    ('"“Teach industry-relevant AME on real hardware.” Curriculum seats seed tomorrow\'s corporate purchases — the LPKF ProtoMat dynamic for 40 years."',
     '"„Lehre industrierelevantes AME auf echter Hardware." Curriculum-Plätze säen die Corporate-Käufe von morgen — die LPKF-ProtoMat-Dynamik seit 40 Jahren."', 1),

    # ---- Slide 11
    ('header(s, "Competitive Landscape", "Alone in the quadrant that matters")',
     'header(s, "Wettbewerbslandschaft", "Allein im Quadranten, auf den es ankommt")', 1),
    ('"PRICE →  high"', '"PREIS →  hoch"', 1),
    ('"low"', '"niedrig"', 1),
    ('"planar (2–2.5 axis)"', '"planar (2–2,5 Achsen)"', 1),
    ('"conformal / 5-axis →"', '"konform / 5-Achs →"', 1),
    ('"Why the quadrant stays open"', '"Warum der Quadrant offen bleibt"', 1),
    ('"Incumbents: cost structures & cannibalization fear block down-market moves"',
     '"Incumbents: Kostenstrukturen & Kannibalisierungsangst blockieren Down-Market-Schritte"', 1),
    ('"Voltera: 12–24 months behind on 5-axis CAM software"',
     '"Voltera: 12–24 Monate Rückstand bei 5-Achs-CAM-Software"', 1),
    ('"New entrants (Hummink, Scrona, Quantica, XTPL) all target sub-micron / display / semiconductor niches"',
     '"Neue Player (Hummink, Scrona, Quantica, XTPL) zielen alle auf Sub-Mikron-/Display-/Halbleiter-Nischen"', 1),
    ('"Real threat: a Bambu-style entrant — window ≈ 3–5 years"',
     '"Echte Gefahr: ein Bambu-artiger Entrant — Zeitfenster ≈ 3–5 Jahre"', 1),

    # ---- Slide 12
    ('header(s, "Product Concept", "KRONOS Eos — one platform, three configurations")',
     'header(s, "Produktkonzept", "KRONOS Eos — eine Plattform, drei Konfigurationen")', 1),
    ('tag: "Teach & enter"', 'tag: "Lehren & einsteigen"', 1),
    ('tag: "The beachhead product"', 'tag: "Das Beachhead-Produkt"', 1),
    ('tag: "Qualify & produce"', 'tag: "Qualifizieren & produzieren"', 1),
    ('"3+2-axis indexed kinematics"', '"3+2-Achs indexierte Kinematik"', 1),
    ('"1 toolhead (micro-dispense) + UV + FFF"', '"1 Werkzeugkopf (Mikrodispens) + UV + FFF"', 1),
    ('"±25 µm deposition accuracy"', '"±25 µm Depositionsgenauigkeit"', 1),
    ('"Camera calibration · Aion-5X Lite"', '"Kamerakalibrierung · Aion-5X Lite"', 1),
    ('"For HAW, colleges, top fab labs"', '"Für HAW, Colleges, Top-FabLabs"', 1),
    ('"TRUE 5-AXIS SIMULTANEOUS printing"', '"ECHTER 5-ACHS-SIMULTANDRUCK"', 1),
    ('"2 toolheads: piezo-jet + dispensing"', '"2 Werkzeugköpfe: Piezo-Jet + Dispensing"', 1),
    ('"±15 µm · AI vision inspection"', '"±15 µm · KI-Vision-Inspektion"', 1),
    ('"Aion-5X Pro · materials starter kit"', '"Aion-5X Pro · Material-Starterkit"', 1),
    ('"For research groups & corporate R&D"', '"Für Forschungsgruppen & Corporate R&D"', 1),
    ('"5-axis + toolchanger (up to 4 heads)"', '"5-Achs + Werkzeugwechsler (bis 4 Köpfe)"', 1),
    ('"SMD placement module · plasma option"', '"SMD-Bestückmodul · Plasma-Option"', 1),
    ('"±10 µm · closed-loop QC"', '"±10 µm · Closed-Loop-QC"', 1),
    ('"Traceability package (defense-ready)"', '"Traceability-Paket (defense-ready)"', 1),
    ('"Upsell path toward Hyperion class"', '"Upsell-Pfad Richtung Hyperion-Klasse"', 1),
    ('"≈ 55% of projected mix"', '"≈ 55 % des geplanten Mixes"', 1),

    # ---- Slide 13
    ('header(s, "Platform Strategy", "Why one platform beats three machines — and why the software is the moat")',
     'header(s, "Plattformstrategie", "Warum eine Plattform drei Maschinen schlägt — und die Software der Burggraben ist")', 1),
    ('"One chassis, three tiers"', '"Ein Chassis, drei Stufen"', 1),
    ('"Shared 5-axis base, B&R control, vision stack. One spare-parts pool, one CE/UL certification, field-upgradeable tiers. R&D: €3.2M instead of €6–8M for three separate machines."',
     '"Gemeinsame 5-Achs-Basis, B&R-Steuerung, Vision-Stack. Ein Ersatzteilpool, eine CE/UL-Zertifizierung, feld-upgradefähige Stufen. F&E: 3,2 M€ statt 6–8 M€ für drei Einzelmaschinen."', 1),
    ('"Aion-5X is the real product"', '"Aion-5X ist das eigentliche Produkt"', 1),
    ('"5-axis deposition CAM + calibration + AI inspection took ~15 years to build. It already exists, scales at zero marginal cost — and licenses to third parties (APES Matrix6D)."',
     '"5-Achs-Depositions-CAM + Kalibrierung + KI-Inspektion brauchten ~15 Jahre. Es existiert bereits, skaliert grenzkostenfrei — und lizenziert an Dritte (APES Matrix6D)."', 1),
    ('"Curated materials program"', '"Kuratiertes Materialprogramm"', 1),
    ('"One silver ink, one dielectric, two polymers — qualified profiles, subscription kits. Cuts support cost, creates the annuity. “Experimental mode” keeps research freedom."',
     '"Eine Silbertinte, ein Dielektrikum, zwei Polymere — qualifizierte Profile, Abo-Kits. Senkt Supportkosten, schafft die Annuität. „Experimental Mode" erhält die Forschungsfreiheit."', 1),
    ('"Cannibalization fence"', '"Kannibalisierungs-Zaun"', 1),
    ('"Build volume, throughput, autonomy and material breadth stay with Helios/Hyperion (€200k+). Eos Max is designed as the feeder, not the killer — the Formlabs-Fuse pattern, not MakerBot."',
     '"Bauraum, Durchsatz, Autonomie und Materialbreite bleiben bei Helios/Hyperion (200 k€+). Eos Max ist als Zubringer gebaut, nicht als Killer — das Formlabs-Fuse-Muster, nicht MakerBot."', 1),

    # ---- Slide 14
    ('header(s, "Business Model", "Machines open the account — the installed base pays the margin")',
     'header(s, "Geschäftsmodell", "Maschinen öffnen den Account — die installierte Basis zahlt die Marge")', 1),
    ('"Revenue mix 2031"', '"Umsatzmix 2031"', 1),
    ('"Machines 74%"', '"Maschinen 74 %"', 1),
    ('"Consumables 11%"', '"Verbrauchsmaterial 11 %"', 1),
    ('"Services/NRE 7%"', '"Services/NRE 7 %"', 1),
    ('"Maintenance 5%"', '"Wartung 5 %"', 1),
    ('"Software 3%"', '"Software 3 %"', 1),
    ('"Revenue mix 2031 · Base"', '"Umsatzmix 2031 · Base"', 1),
    ('"Per installed machine, per year (Base)"', '"Je installierte Maschine, pro Jahr (Base)"', 1),
    ('"consumables\\n(curated ink kits)"', '"Verbrauchsmaterial\\n(kuratierte Tinten-Kits)"', 1),
    ('"service contract\\n(11% · 50% attach)"', '"Servicevertrag\\n(11 % · 50 % Attach)"', 1),
    ('"Aion-5X seat\\n(60% attach)"', '"Aion-5X-Seat\\n(60 % Attach)"', 1),
    ('"recurring per unit\\n— growing with base"', '"wiederkehrend je Einheit\\n— wächst mit der Basis"', 1),
    ('"Financing built for SME budgets"', '"Finanzierung für KMU-Budgets gebaut"', 1),
    ('"Leasing via partners (Grenke/DLL class), balance-sheet neutral: Eos Five ≈ €1.3–1.5k/month — an OPEX decision. German equipment-leasing share: 26.1% of all equipment investment (BDL 2024)."',
     '"Leasing über Partner (Grenke/DLL-Klasse), bilanzneutral: Eos Five ≈ 1,3–1,5 k€/Monat — eine OPEX-Entscheidung. Deutsche Leasingquote: 26,1 % aller Ausrüstungsinvestitionen (BDL 2024)."', 1),
    ('"30% down-payment standard keeps working capital at 12% of revenue growth. Machine-as-a-Service tier follows the Carbon precedent (~35–45% of sale price per year)."',
     '"30 % Anzahlung als Standard hält das Working Capital bei 12 % des Umsatzzuwachses. Machine-as-a-Service folgt dem Carbon-Präzedenzfall (~35–45 % des Kaufpreises pro Jahr)."', 1),

    # ---- Slide 15
    ('header(s, "TAM · SAM · SOM", "Sized bottom-up from counted organizations — not from analyst headlines")',
     'header(s, "TAM · SAM · SOM", "Bottom-up aus gezählten Organisationen — nicht aus Analysten-Schlagzeilen")', 1),
    ('"10-yr equipment + attach potential · ~10,000 organizations worldwide × 1.3 machines × €65k"',
     '"10-Jahres-Equipment- + Attach-Potenzial · ~10.000 Organisationen weltweit × 1,3 Maschinen × 65 k€"', 1),
    ('"EU + North America, reachable segments 2027–2031 · ~4,200 organizations · ≈€35–45M/yr by 2031"',
     '"EU + Nordamerika, erreichbare Segmente 2027–2031 · ~4.200 Organisationen · ≈35–45 M€/Jahr bis 2031"', 1),
    ('"KRONOS cumulative 5-yr (Base): 452 units + attach ≈ 30% of the matured band"',
     '"KRONOS kumuliert 5 Jahre (Base): 452 Einheiten + Attach ≈ 30 % des gereiften Bandes"', 1),
    ('"Reality check: "', '"Realitäts-Check: "', 1),
    ('"today\'s entire AME machine market is ~€15–28M/yr. Every euro of SAM beyond that assumes the band expands 5–7x by 2031 — the Conservative case assumes zero expansion and is a documented no-go."',
     '"Der gesamte heutige AME-Maschinenmarkt liegt bei ~15–28 M€/Jahr. Jeder SAM-Euro darüber hinaus unterstellt eine 5–7x-Band-Expansion bis 2031 — der Konservativ-Fall unterstellt null Expansion und ist ein dokumentiertes No-Go."', 1),

    # ---- Slide 16
    ('header(s, "5-Year Financial Case", "Base case: €16M revenue, 50% gross margin, EBITDA break-even 2031")',
     'header(s, "5-Jahres-Finanz-Case", "Base Case: 16 M€ Umsatz, 50 % Bruttomarge, EBITDA-Break-even 2031")', 1),
    ('{ name: "Machines", labels: years', '{ name: "Maschinen", labels: years', 1),
    ('{ name: "Recurring (mat.+svc+SW)", labels: years', '{ name: "Wiederkehrend (Mat.+Svc+SW)", labels: years', 1),
    ('{ name: "Application projects", labels: years', '{ name: "Applikationsprojekte", labels: years', 1),
    ('"Base case anchors"', '"Base-Case-Anker"', 1),
    ('"units/yr, 2027 → 2031 (cum. 452)"', '"Einheiten/Jahr, 2027 → 2031 (kum. 452)"', 1),
    ('"gross margin as COGS falls 58% → 48%"', '"Bruttomarge bei COGS-Senkung 58 % → 48 %"', 1),
    ('"gross funding need (peak cash + 15% buffer)"', '"Brutto-Kapitalbedarf (Cash-Tal + 15 % Puffer)"', 1),
    ('"XTPL check"', '"XTPL-Check"', 1),
    ('"comparable needed €15–18M for 13 units/yr — Eos starts with finished core tech"',
     '"Vergleichsunternehmen brauchte 15–18 M€ für 13 Einheiten/Jahr — Eos startet mit fertiger Kerntechnik"', 1),

    # ---- Slide 17
    ('header(s, "Scenarios & Returns", "Three futures, honestly priced — including the one where you lose")',
     'header(s, "Szenarien & Returns", "Drei Zukünfte, ehrlich bepreist — inklusive der, in der Sie verlieren")', 1),
    ('name: "CONSERVATIVE"', 'name: "KONSERVATIV"', 1),
    ('sub: "No band expansion — today\'s demand only"', 'sub: "Keine Band-Expansion — nur heutige Nachfrage"', 1),
    ('sub: "Band expands 5–7x — Formlabs-calibrated"', 'sub: "Band expandiert 5–7x — Formlabs-kalibriert"', 1),
    ('sub: "Market creation: defense, IME, attach economy"', 'sub: "Marktschaffung: Defense, IME, Attach-Ökonomie"', 1),
    ('["Units cum. 2031", "178"]', '["Einheiten kum. 2031", "178"]', 1),
    ('["Units cum. 2031", "452"]', '["Einheiten kum. 2031", "452"]', 1),
    ('["Units cum. 2031", "743"]', '["Einheiten kum. 2031", "743"]', 1),
    ('["Revenue 2031", "€4.9M"]', '["Umsatz 2031", "4,9 M€"]', 1),
    ('["Revenue 2031", "€16.0M"]', '["Umsatz 2031", "16,0 M€"]', 1),
    ('["Revenue 2031", "€29.1M"]', '["Umsatz 2031", "29,1 M€"]', 1),
    ('["EBITDA 2031", "−€0.9M"]', '["EBITDA 2031", "−0,9 M€"]', 1),
    ('["EBITDA 2031", "+€1.1M"]', '["EBITDA 2031", "+1,1 M€"]', 1),
    ('["EBITDA 2031", "+€6.8M (23%)"]', '["EBITDA 2031", "+6,8 M€ (23 %)"]', 1),
    ('["Break-even", "none"]', '["Break-even", "keiner"]', 1),
    ('["Break-even", "2031"]', '["Break-even", "2031"]', 1),
    ('["Break-even", "2030"]', '["Break-even", "2030"]', 1),
    ('["MOIC / IRR (yr 7)", "0.3x / −18%"]', '["MOIC / IRR (J7)", "0,3x / −18 %"]', 1),
    ('["MOIC / IRR (yr 7)", "2.25x / +14%"]', '["MOIC / IRR (J7)", "2,25x / +14 %"]', 1),
    ('["MOIC / IRR (yr 7)", "11.4x / +48%"]', '["MOIC / IRR (J7)", "11,4x / +48 %"]', 1),
    ('verdict: "NOT INVESTABLE — this is the documented no-go scenario the gates protect against."',
     'verdict: "NICHT INVESTIERBAR — das dokumentierte No-Go-Szenario, vor dem die Gates schützen."', 1),
    ('verdict: "A solid LPKF-class business — below venture threshold on its own."',
     'verdict: "Ein solides Geschäft der LPKF-Klasse — für sich allein unter der Venture-Schwelle."', 1),
    ('verdict: "Venture-grade. ~25–30% probability carries the deal\'s expected value (≈3x blended)."',
     'verdict: "Venture-tauglich. ~25–30 % Wahrscheinlichkeit tragen den Erwartungswert (≈3x blended)."', 1),

    # ---- Slide 18
    ('header(s, "Go-to-Market", "Community-led, direct-first — a sales army comes later, if ever")',
     'header(s, "Go-to-Market", "Community-geführt, direkt zuerst — eine Vertriebsarmee kommt später, wenn überhaupt")', 1),
    ('"Research beachhead (EU/NA)"', '"Forschungs-Beachhead (EU/NA)"', 1),
    ('"LOPEC · productronica · Formnext presence — award momentum"',
     '"LOPEC · productronica · Formnext — Award-Momentum"', 1),
    ('"Paper-reference program: discount for citability"', '"Paper-Referenzprogramm: Rabatt gegen Zitierbarkeit"', 1),
    ('"Demo tours via FAPS / Fraunhofer network"', '"Demo-Touren über das FAPS-/Fraunhofer-Netz"', 1),
    ('"Inside sales + 2 application engineers · CAC ≈ €9k"', '"Inside Sales + 2 Application Engineers · CAC ≈ 9 k€"', 1),
    ('"Corporate R&D expansion"', '"Corporate-R&D-Expansion"', 1),
    ('"Reference-driven entry: ZVEI / CLEPA / SPECTARIS segments"',
     '"Referenzgetriebener Einstieg: ZVEI-/CLEPA-/SPECTARIS-Segmente"', 1),
    ('"Channel activation: APES & NTV (NA), ex-Neotech partners (JP/AU)"',
     '"Kanal-Aktivierung: APES & NTV (NA), Ex-Neotech-Partner (JP/AU)"', 1),
    ('"25% of volume through distributors at 30% discount"', '"25 % des Volumens über Distributoren mit 30 % Rabatt"', 1),
    ('"electronica · SMTconnect · IME consortia"', '"electronica · SMTconnect · IME-Konsortien"', 1),
    ('"Defense · education · small series"', '"Defense · Ausbildung · Kleinserie"', 1),
    ('"Eos Max + traceability into SBIR / NextFlex ecosystem"',
     '"Eos Max + Traceability ins SBIR-/NextFlex-Ökosystem"', 1),
    ('"Eos One curriculum bundles for HAW & colleges"', '"Eos-One-Curriculum-Bundles für HAW & Colleges"', 1),
    ('"First production-cell clusters — Hyperion feeder"', '"Erste Produktionszellen-Cluster — Hyperion-Zubringer"', 1),
    ('"APAC entry via reactivated distributor network"', '"APAC-Einstieg über reaktiviertes Distributorennetz"', 1),

    # ---- Slide 19
    ('header(s, "Validation Roadmap", "Six gates, hard kill criteria — €2.5M buys the truth before the factory")',
     'header(s, "Validierungsfahrplan", "Sechs Gates, harte Kill-Kriterien — 2,5 M€ kaufen die Wahrheit vor der Fabrik")', 1),
    ('"Discovery", "40 interviews · ≥30% budget-backed intent"', '"Discovery", "40 Interviews · ≥30 % budgetgedeckte Kaufabsicht"', 1),
    ('"Demand test", "≥10 LOIs (3 with deposit intent) · price test"', '"Demand-Test", "≥10 LOIs (3 mit Anzahlungsabsicht) · Preistest"', 1),
    ('"Cost & IP", "BOM ≤€26k · patent chain-of-title cleared"', '"Kosten & IP", "BOM ≤26 k€ · Patent-Titel geklärt"', 1),
    ('"Design partners", "5 paid pilots · ≥4 accept · service <10%"', '"Design-Partner", "5 bezahlte Piloten · ≥4 Abnahmen · Service <10 %"', 1),
    ('"Pilot fleet", "10 machines · ≥30 pre-orders · failures <5%/q"', '"Pilotflotte", "10 Maschinen · ≥30 Pre-Orders · Ausfälle <5 %/Q"', 1),
    ('"Series release", "unit cost on plan · delivery >90%"', '"Serienfreigabe", "Stückkosten im Plan · Liefertreue >90 %"', 1),
    ('"TRANCHE 1 — €2.5M"', '"TRANCHE 1 — 2,5 M€"', 1),
    ('"Q4 2026 · funds G0–G4 through pilot fleet"', '"Q4 2026 · finanziert G0–G4 bis zur Pilotflotte"', 1),
    ('"The only commitment requested today"', '"Das einzige heute erbetene Commitment"', 1),
    ('"TRANCHE 2 — €4.5M"', '"TRANCHE 2 — 4,5 M€"', 1),
    ('"Q4 2027 · industrialization & launch"', '"Q4 2027 · Industrialisierung & Launch"', 1),
    ('"Unlocked by: ≥10 LOIs · BOM ≤€26k · IP cleared"', '"Freigeschaltet durch: ≥10 LOIs · BOM ≤26 k€ · IP geklärt"', 1),
    ('"TRANCHE 3 — €4–5M"', '"TRANCHE 3 — 4–5 M€"', 1),
    ('"Q1 2029 · scale & channel build-out"', '"Q1 2029 · Skalierung & Kanalausbau"', 1),
    ('"Unlocked by: ≥60 units sold · GM ≥42% · service <8%"', '"Freigeschaltet durch: ≥60 verkaufte Einheiten · GM ≥42 % · Service <8 %"', 1),

    # ---- Slide 20
    ('header(s, "Investment Thesis — Decision", "Substance over optimism", { noTrace: true })',
     'header(s, "Investment-These — Entscheidung", "Substanz vor Optimismus", { noTrace: true })', 1),
    ('"THE BET"', '"DIE WETTE"', 1),
    ('"For €2.5M, the investor buys the option on the only unclaimed Formlabs position in 3D-printed electronics — proven 5-axis technology, a vacant price band, a cleared field, and procurement rules that just tilted in its favor."',
     '"Für 2,5 M€ kauft der Investor die Option auf die einzige unbesetzte Formlabs-Position der 3D-gedruckten Elektronik — bewiesene 5-Achs-Technologie, ein leeres Preisband, ein bereinigtes Feld und Vergaberegeln, die sich gerade zu ihren Gunsten gedreht haben."', 1),
    ('"GO — conditionally"', '"GO — unter Bedingungen"', 1),
    ('"Commit T1 after three pre-closing checks: IP chain-of-title, software-team retention, insolvency legacy clean."',
     '"T1 nach drei Pre-Closing-Prüfungen committen: IP-Titel, Bindung des Software-Teams, saubere Insolvenz-Altlasten."', 1),
    ('"STOP at the gates if"', '"STOPP an den Gates, wenn"', 1),
    ('"<10 LOIs in 6 months · BOM >€32k · NOVA proxy <30 units/yr · service cost >12% in pilots."',
     '"<10 LOIs in 6 Monaten · BOM >32 k€ · NOVA-Proxy <30 Einheiten/Jahr · Servicekosten >12 % in Piloten."', 1),
    ('"DO NOT invest at all if"', '"GAR NICHT investieren, wenn"', 1),
    ('"you require a certain venture return: only the Upside path (~25–30% probability) is venture-grade. This is an option, not a promise."',
     '"Sie einen sicheren Venture-Return brauchen: Nur der Upside-Pfad (~25–30 % Wahrscheinlichkeit) ist venture-tauglich. Das ist eine Option, kein Versprechen."', 1),
    ('"WHAT THE SKEPTIC SAYS"', '"WAS DER SKEPTIKER SAGT"', 1),
    ('"Every predecessor failed or stayed small — maybe the gap is absent demand, not market failure."',
     '"Jeder Vorgänger scheiterte oder blieb klein — vielleicht ist die Lücke fehlende Nachfrage, kein Marktversagen."', 1),
    ('"Zero verified KRONOS sales since relaunch — execution by a ~6-person team is unproven."',
     '"Null verifizierte KRONOS-Verkäufe seit Relaunch — die Ausführung durch ein ~6-Personen-Team ist unbewiesen."', 1),
    ('"Academic beachheads are grant-cyclical and don\'t reorder — the corporate/defense jump must actively succeed."',
     '"Akademische Beachheads sind förderzyklisch und bestellen nicht nach — der Corporate-/Defense-Sprung muss aktiv gelingen."', 1),
    ('"These are not dismissed — they are the gates. If they hold, the loss is €2.5M and a clean stop. If they fall, the position is category-defining."',
     '"Diese Argumente werden nicht weggewischt — sie sind die Gates. Halten sie, ist der Verlust 2,5 M€ und ein sauberer Stopp. Fallen sie, ist die Position kategorie-definierend."', 1),
]

src = open(SRC, encoding='utf-8').read()
src = src.replace(
    "/* Erzeugt presentation/kronos-investor-deck-de.pptx" if False else "/* Erzeugt presentation/kronos-investor-deck.pptx — 20 Slides, Premium Industrial Design.",
    "/* Erzeugt presentation/kronos-investor-deck-de.pptx — deutsche Ausgabe (20 Slides).", 1)

missing = []
for en, de_, cnt in T:
    found = src.count(en)
    if found != cnt:
        missing.append((en[:80], found, cnt))
        continue
    src = src.replace(en, de_)

if missing:
    print("FEHLER — folgende Strings nicht wie erwartet gefunden:")
    for m in missing:
        print(f"  count={m[1]} erwartet={m[2]} :: {m[0]}")
    raise SystemExit(1)

# Deutsche Zitate: ASCII-Schließzeichen nach „…" würde JS-Strings sprengen → typografisches “
import re
src = re.sub(r'„([^„"\n]*?)"', '„\\1“', src)

open(DST, 'w', encoding='utf-8').write(src)
print(f"{DST} geschrieben ({len(T)} Übersetzungen).")
